### ISSUE TITLE
为什么文件无论设置了私有还是公共，分享出去下载都需要登录

### ISSUE THREAD

**Issue by nbnb666888** [eyebluecn/tank#102]
分享了一个文件，无论设置私有还是公共，为何下载者都要登录才能下载？那这多不方便啊，分享给人家，人家还要注册登录才能下载

**Comment by zicla** [comment]
分享的文件需要登录的问题在3.1.1版本修复了，过两天发布。

**Comment by zicla** [comment]
3.1.1版本已经发布，修复了该问题。
