### ISSUE TITLE
日志系统锁机制有问题，多线程下，日志切割时，会导致下面报错

### ISSUE THREAD

**Issue by lzle** [eyebluecn/tank#109]
lian@liandeMacBook-Pro go-callin % go run main.go
use log file ./log/callin.log
use log file ./log/callin.log
occur error while logging write ./log/callin.log: file already closed
occur error while logging write ./log/callin.log: file already closed

**Comment by zicla** [comment]
无法复现该问题，并且也未曾收到其他用户反馈
