### ISSUE TITLE
文件删除以后，文件的分享链接未被删除

### ISSUE THREAD

**Issue by aurthurxlc** [eyebluecn/tank#111]
问题：文件删除以后，文件的分享链接未被删除，就算是从回收站删除也不行

解决方案：删除文件时检测一下文件分享状态，如果文件被分享了提示一下用户 “当前文件被分享了，是否需要继续删除”

**Comment by zicla** [comment]
分享的链接没有删除，但是分享的文件确实不在了，不影响用户使用，这一项属于可改可不改的点，后续看大家的反馈情况吧
