### ISSUE TITLE
“我的分享”加载不出来

### ISSUE THREAD

**Issue by RikudouPatrickstar** [eyebluecn/tank#114]
分享文件后，“我的分享”一片空白不显示任何东西。演示站也是一样

**Comment by zicla** [comment]
@seaheart 有时间看一下这个问题。

**Comment by seaheart** [comment]
@RikudouPatrickstar 你好，现在还有这种问题吗，如果可以的话麻烦提供下完整的复现操作

**Comment by RikudouPatrickstar** [comment]
@seaheart 你好，感谢回复！刚刚重新试了一遍，在 Windows10 Chrome 上进入演示站，随意勾选一个文件分享，再点击左侧菜单栏“我的分享”，依旧一片空白。不过在 Android Phone Chrome 上进入演示站，同样勾选一个文件分享，再点击左侧菜单栏“我的分享”，却能够看到分享的内容。
