### ISSUE TITLE
希望回收站文件移动到其他位置

### ISSUE THREAD

**Issue by Towdium** [eyebluecn/tank#116]
我这里使用场景可能有点特殊：在内网里用 Samba/NFS 直接挂载驱动器，在外网使用蓝眼作为前端。
在这种场景下，直接挂载的场景就能够看到回收站里的内容，和网页中的内容不一致。
WebDAV 确实是一个好的替代方案，但是目前的 WebDAV 实现中，内网写入文件大约只有一个文件每秒，我的小文件又比较多，所以不是很方便。

与此同时，这也可以解决 #112 。

当然，从我个人角度来说，如果可以完全禁用回收站也是可以接受的。
不过即使我把回收站保留天数调整为 0，文件似乎还是会先进入回收站。

**Comment by zicla** [comment]
下个版本考虑增加一个功能，当保留天数设为0时，采用硬删除的方式。

**Comment by zicla** [comment]
3.1.2版本在删除时候增加了彻底删除的选项，因此能够解决掉回收站体验问题。  另外WebDAV中也已经设置为了只能看到未删除的文件。

**Comment by zicla** [comment]
3.1.2版本 webdav中的策略调整成了直接硬删除文件
