### ISSUE TITLE
分享过期依旧能下载

### ISSUE THREAD

**Issue by hsy-design** [eyebluecn/tank#120]
分享过期依旧能下载
![image](https://user-images.githubusercontent.com/52811347/98773170-5137d180-2423-11eb-8a19-61506bc67fbf.png)
删除分享后才正常

建议与我接下来的尝试：
1、在输入提取码之后若过期直接跳到一个过期的特定页面，若没过期则如往常一样
2、通过研读代码，参考一次性链接更改分享模块的代码，以完善逻辑

**Comment by zicla** [comment]
无法复现该问题。 如果分享过期了，是无法下载的。
