### ISSUE TITLE
软连接

### ISSUE THREAD

**Issue by Jimmy39** [eyebluecn/tank#128]
建议增加对于软连接的支持，以方便在多个硬盘的场景下应用。
我现在使用的是3.1.2，直接使用ln -s在物理根目录下建立一个软连接，扫描之后会被认为成一个无拓展名的文件。
先在网页中建立一个文件夹，然后删除文件夹，用同名软连接代替，则可以正常从网页向被链接文件夹上传下载文件，但是扫描无法扫描到文件夹中的原有文件或者其他途径放进来的文件。

**Comment by Jimmy39** [comment]
另外如果支持软连接的话，组文件夹等功能也能靠软连接轻松的实现

**Comment by zicla** [comment]
抱歉，目前还没有在计划中
