### ISSUE TITLE
大文件上传不了

### ISSUE THREAD

**Issue by sjatsh** [eyebluecn/tank#13]
文件上传，选择一个1G文件后上传没有反应。

**Comment by MomokaKawakabe** [comment]
是的，无法上传超巨大文件。

**Comment by sjatsh** [comment]
1G算超巨大文件？

**Comment by zicla** [comment]
是在 tank.eyeblue.cn 这个网站上上传还是在你自己部署的网站上传？ tank.eyeblue.cn 这个网站对于demo账号有大小限制的，不允许上传超过1M的文件。

**Comment by MomokaKawakabe** [comment]
在自己部署的网站上传，确实上传不了超巨大文件。

**Comment by zicla** [comment]
@MomokaKawakabe OK，这个问题这两天我紧跟一下

**Comment by sjatsh** [comment]
@MomokaKawakabe 我暂时自己改了前端代码，去除了上传1G的限制。
