### ISSUE TITLE
才发现这个云盘。没有linux arm64啊😱？

### ISSUE THREAD

**Issue by niubility000** [eyebluecn/tank#131]
想试用都不行啊，我不会编译啊😱。。
官方能出个arm64版吗？

**Comment by zicla** [comment]
我没有arm64的设备，所以发布包就没有打这个。。 你可以加入群里，和群友交流一下，群友有。

**Comment by RikudouPatrickstar** [comment]
```shell
git clone -b master https://github.com/eyebluecn/tank tank
cd tank
docker build -t eyeblue/tank:latest .
```
这样子自己 build 一个 image 出来就好了 @niubility000

**Comment by zicla** [comment]
有的版本有arm64，你可以从这里找一下：  https://tank-doc.eyeblue.cn/basic/download.html
