### ISSUE TITLE
自定义预览引擎跳转链接格式支持

### ISSUE THREAD

**Issue by zpoint** [eyebluecn/tank#133]
![image](https://user-images.githubusercontent.com/18083296/108955606-6f130480-76a9-11eb-8749-da778ea6a1e3.png)

文档里贴了 kkfileview 的链接 , 但是目前 kkfileview 的最新版需要 urlencode + base64encode 两步, 而自定义的预览引擎只做了urlencode, 是否可以配置化支持一下呢

![image](https://user-images.githubusercontent.com/18083296/108955489-3b37df00-76a9-11eb-800b-937187482ee4.png)

https://tank-doc.eyeblue.cn/advance/preview.html
https://kkfileview.keking.cn/zh-cn/docs/home.html

**Comment by TxWuu** [comment]
![image](https://user-images.githubusercontent.com/45418316/109274398-69a2ef00-784e-11eb-88ca-56b96991d4ec.png)

自己改吧,这个还是容易的.
修改路径和咋改都给了,前端打包的方式文档里面有,也非常简单,编译以后替换就可以了.
而且这个涉及到调用方的接口问题,起码微软和KK那边的接口现在完全不一样了,urlencode只是转义一下不影响内容,加上base64编码就不行了,估计想做一个非常易用的接口不太现实的,除非枚举出常用的编码方式做一组开关

**Comment by zpoint** [comment]
好的谢谢

**Comment by wen2006953** [comment]
为了支持两种,我是这样改的,作两个变量
![image](https://user-images.githubusercontent.com/37644488/109288820-56991a80-7860-11eb-9650-3baa03e30204.png)

**Comment by wen2006953** [comment]
为了支持两种方式, 我是这样改的, 做两个内置变量, 如下

![image](https://user-images.githubusercontent.com/37644488/109289138-bdb6cf00-7860-11eb-8ef1-0d7fb0a7c76d.png)

**Comment by zpoint** [comment]
@wen2006953  谢谢😁
