### ISSUE TITLE
webdav Windows打不开

### ISSUE THREAD

**Issue by wen2006953** [eyebluecn/tank#134]
1、打开我的电脑在空白处右击点增加一个网络位置，然后输入http://xxx.xxx.xxx.xxx:6010/api/dav确定，进示输入的文件夹无效。https://tank.eyeblue.cn/api/dav样便地址同样是这个错。
![image](https://user-images.githubusercontent.com/37644488/109281462-4a5c8f80-7857-11eb-886b-c3e9c132cf20.png)
2、共享组，是不是就是共享目录，加入的用户都可以访问修改，相互可见。issues中有人说只持，可是没看到哪里有设置。
3、文件列表每一行点击空白处会打开文件，能不能改为自动勾选多选框，点击文件名的时候，再打开文件。别外选中这一行的时候要高亮，别无变化。

**Comment by andylhj** [comment]
我的也是啊，webdav功能很关键的

**Comment by zicla** [comment]
https://tank-doc.eyeblue.cn/advance/webdav.html  参考这里，我暂时不确定windows自身的webdav是否可用。
