### ISSUE TITLE
请问数据库不使用外键是什么考虑，还是我没找到？

### ISSUE THREAD

**Issue by biluohc** [eyebluecn/tank#14]

**Comment by MomokaKawakabe** [comment]
使用JPA和hibernate查表，外键自然没必要了。除非很有必要加锁

**Comment by zicla** [comment]
外键一般建议在开发阶段开启，在生产阶段移除。 因为外键的逻辑关系代码中就直接保证了，没有必要再在数据库这一层保证了。
