### ISSUE TITLE
能将文件分享给指定的一些用户吗？对应用户登录后就能看到我分享给他的文件

### ISSUE THREAD

**Issue by zl-fire** [eyebluecn/tank#140]
能将文件分享给指定的一些用户吗？对应用户登录后就能看到我分享给他的文件
![image](https://user-images.githubusercontent.com/25565146/117955615-d0627f80-b34a-11eb-8d2d-7864bd551cbf.png)

**Comment by zicla** [comment]
抱歉，该功能暂时没在计划中
