### ISSUE TITLE
上传文件缓存错误，提示bufio: buffer full

### ISSUE THREAD

**Issue by eeput** [eyebluecn/tank#141]
系统：`DietPi_VMware-x86_64-Buster V7.2`
云盘：`tank-3.1.2.linux-amd64`
数据库：`MariaDB Server version: 10.3.27`
错误信息：`[ERROR] 18:43:32 tank_router.go:98 panic on matter_controller.go:239 multipart: NextPart: bufio: buffer full`
错误描述：使用管理员账号上传3.2G的文件，当文件上传到1G时进度条不动，过几秒钟后shell报错。

**Comment by Rabbit0w0** [comment]
缓冲区满了呗

**Comment by eeput** [comment]
确实是缓冲区满了，和内存大小与swap大小有关，可以更改文件缓存方式，这样小内存也可以上传大文件
