### ISSUE TITLE
Docker方式部署怎么升级呢？

### ISSUE THREAD

**Issue by 16it** [eyebluecn/tank#144]
我最开始部署的3.0.6，然后升级到3.1x，我的做法是先删除docker，然后重新拉去镜像并run起来，但是我发现重新运行后打开页面又进入引导页面了，然后重新初始化，然后以前的数据和配置都丢了。烦劳官方指导！

**Comment by zicla** [comment]
新进入引导页面没关系，只要你的文件本身没有丢失即可。  文件在 matter 文件夹下
