### ISSUE TITLE
文件预览设置问题

### ISSUE THREAD

**Issue by xudong198600** [eyebluecn/tank#146]
现在微软的接口已经无法预览，准备换成推荐的kkFileView，docker已经部署kkFileView，具体需要怎么设置才可以使用kkFileView？我看kkFileView说明文档里面需要使用代码才可以实现，而不是单纯的http传参数。请问需要怎么填写这个格式呢？

**Comment by xudong198600** [comment]
作者已经好久没回复了，不知道还会不会维护

**Comment by huaxuanHan** [comment]
就怕作者不再维护了，很好用的云盘工具

**Comment by zicla** [comment]
会一直维护的，请放心。 只是最近工作有点太忙了，稍微空闲了就会继续升级迭代。

**Comment by biuaxia** [comment]
> 现在微软的接口已经无法预览，准备换成推荐的kkFileView，docker已经部署kkFileView，具体需要怎么设置才可以使用kkFileView？我看kkFileView说明文档里面需要使用代码才可以实现，而不是单纯的http传参数。请问需要怎么填写这个格式呢？

我已 Fork 此仓库，将适配 kkFileView-v4.0.0 的代码已提交至本仓库的 pull request，如果顺利通过应该很快就能看到相关的发布。

如果急需使用此功能，可以前往 fork 仓库的 Release -> [Release Tank3.1.2 · biuaxia/tank](https://github.com/biuaxia/tank/releases/tag/Tank3.1.2)

**Comment by xudong198600** [comment]
使用docker安装的如何升级呢？ @biuaxia

**Comment by biuaxia** [comment]
> 使用docker安装的如何升级呢？ @biuaxia

pr已经合并，等待官方打包即可。

**Comment by xudong198600** [comment]
使用最新的蓝眼，设置了KK，但KK出现以下情况，是什么原因？我设置的预览为：http://127.0.0.1:8012/onlinePreview?url={b64Url}
![image](https://user-images.githubusercontent.com/54304722/145153321-dcc8cbc6-2298-46e9-b8f5-948e9aeaf91c.png)
@biuaxia

**Comment by biuaxia** [comment]
> 使用最新的蓝眼，设置了KK，但KK出现以下情况，是什么原因？我设置的预览为：[http://127.0.0.1:8012/onlinePreview?url={b64Url}](http://127.0.0.1:8012/onlinePreview?url=%7Bb64Url%7D) [ ![image](https://user-images.githubusercontent.com/54304722/145153321-dcc8cbc6-2298-46e9-b8f5-948e9aeaf91c.png) ](https://user-images.githubusercontent.com/54304722/145153321-dcc8cbc6-2298-46e9-b8f5-948e9aeaf91c.png) @biuaxia

请贴上kkFileView的日志。

**Comment by biuaxia** [comment]
> > > 使用最新的蓝眼，设置了KK，但KK出现以下情况，是什么原因？我设置的预览为：[http://127.0.0.1:8012/onlinePreview?url={b64Url}](http://127.0.0.1:8012/onlinePreview?url=%7Bb64Url%7D) [ ![image](https://user-images.githubusercontent.com/54304722/145153321-dcc8cbc6-2298-46e9-b8f5-948e9aeaf91c.png) ](https://user-images.githubusercontent.com/54304722/145153321-dcc8cbc6-2298-46e9-b8f5-948e9aeaf91c.png) @biuaxia
> > 
> > 
> > 请贴上kkFileView的日志。
> 
> 好像是抛出异常了，我使用docker安装的kk，kk演示页面打开没有任何问题。下面是异常： 2021-12-10 01:41:56.320 WARN 1 --- [qtp416153648-20] org.eclipse.jetty.server.HttpChannel : /onlinePreview
> 
> java.lang.IllegalArgumentException: Illegal base64 character 7b at java.util.Base64$Decoder.decode0(Base64.java:714) ~[na:1.8.0_251] at java.util.Base64$Decoder.decode(Base64.java:526) ~[na:1.8.0_251] at org.springframework.util.Base64Utils.decode(Base64Utils.java:59) ~[spring-core-5.3.3.jar!/:5.3.3] at org.springframework.util.Base64Utils.decodeFromString(Base64Utils.java:111) ~[spring-core-5.3.3.jar!/:5.3.3] at cn.keking.web.filter.TrustHostFilter.doFilter(TrustHostFilter.java:39) ~[classes!/:na] at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at cn.keking.web.filter.ChinesePathFilter.doFilter(ChinesePathFilter.java:21) ~[classes!/:na] at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.3.jar!/:5.3.3] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar!/:5.3.3] at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.3.jar!/:5.3.3] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar!/:5.3.3] at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.3.jar!/:5.3.3] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar!/:5.3.3] at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) ~[jetty-security-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) [jetty-util-9.4.35.v20201120.jar!/:9.4.35.v20201120] at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) [jetty-util-9.4.35.v20201120.jar!/:9.4.35.v20201120] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_251] 麻烦你帮忙看一下什么问题，十分感谢！

是所有文件都有此问题吗？如果方便可以添加我的 dingtalk: dawnme

**Comment by biuaxia** [comment]
给后来的朋友留个参考。

提出问题的朋友看到了[issue#146](https://github.com/eyebluecn/tank/issues/146#issuecomment-973666112)，但是此功能只是合并了pr，如果想要使用还需要等待官方的软件包。截至（2021年12月10日10点16分）此功能还未在官方包提供。

**Comment by zicla** [comment]
请参考这里：  https://tank-doc.eyeblue.cn/advance/preview.html
