### ISSUE TITLE
一个搜索页面很明显的Bug，没人发现吗？

### ISSUE THREAD

**Issue by steinvenic** [eyebluecn/tank#148]
问题描述：点击搜索结果页的某个目录，点进去空白，实际上目录里面有文件

复现步骤：
- 创建目录`JUST_TEST`,并进入该目录，在目录下上传文件`file.txt`

- 在搜索框搜索`JUST_TEST`，并进入`JUST_TEST`目录

- 期望结果：`JUST_TEST`目录下存在文件`file.txt`

- 实际结果：`JUST_TEST`目录为空

**Comment by zicla** [comment]
Fixed in Tank3.1.3
