### ISSUE TITLE
三个问题

### ISSUE THREAD

**Issue by ZWC-father** [eyebluecn/tank#151]
1、更新头像后，头像会和其他文件存在一起，如果删除，头像就无法显示。希望能将头像图片单独存放。
2、希望增加在线文件压缩、解压功能。
3、搜索文件夹时，搜到的文件夹打开都是空的（文件夹里本来有文件）。

**Comment by zicla** [comment]
1. 您可以使用一个图片url来作为头像。
2. 这个短时间可能没法支持。
3. 这个问题在3.1.3版本修复了。
