### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [eyebluecn/tank#156]
Hey there!

I belong to an open source security research community, and a member (@veloideu) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Veloideu** [comment]
@JamieSlome  
Hello.

I created SECURITY.md as you requested.

thank you.

url : https://github.com/Veloideu/tank/blob/ca59b6f36a786aeeccdc8d5b3fca4d6dbfb8e280/SECURITY.md

**Comment by zicla** [comment]
I add SECURITY.md file in the root folder.

**Comment by JamieSlome** [comment]
@zicla - amazing, thanks for your support! 👍 

We have sent an e-mail to your elected e-mail address, but just for reference, you can find the report here:

https://huntr.dev/bounties/29490465-e38c-4e33-a8b7-48ceb1241e12/

It is private and only accessible to maintainers with repository write permissions. Let me know if you have any questions.
