### ISSUE TITLE
可能存在时区配置错误问题

### ISSUE THREAD

**Issue by zicla** [eyebluecn/tank#164]
在使用docker版本的时候，发现时间偏移了8小时。

**Comment by seaheart** [comment]
初始化时优化报错提示
![](https://media-image1.baydn.com/storage_media_image/kzlbpl/6623f965e2ee871b7f2a632d5566ddea.8b32883452289b36ae4d41b89a26ba40.png?x-oss-process=image/format,jpg)

**Comment by seaheart** [comment]
fixed
