### ISSUE TITLE
实际使用时候有几个问题

### ISSUE THREAD

**Issue by huaxuanHan** [eyebluecn/tank#177]
在测试的时候没发现问题，实际一用下来有几个问题，导致无法使用。
1、我们是放在内网服务器上面的，同时服务器上面还放的有web服务，只要打开蓝眼云盘，我们的web服务访问就会出现问题，有50%的概率访问不了，就是访问服务老是出错，而且打开蓝颜云盘的话，资源占用比较大
2、这个问题直接导致我们放弃使用了，我上传一个2.24G的压缩文件，第一次提示文件大于100M，但是还会继续上传，服务器上面还会有文件，这个可能也不是啥问题，问题是服务器上面有文件，我在我电脑上无论是刷新，重新打开网页都刷新不出来文件，第二次，取消了100M文件大小的限制，上传，显示完成，服务器上面还是有文件，可是我在网页上面还是看不到我上传的文件。
这两个问题导致我们放弃使用了，还是用U盘拷贝直接快速

**Comment by zicla** [comment]
谢谢你的反馈，问题1我们需要再排查一下，我们在下个版本修复问题2.
