### ISSUE TITLE
希望增加限速功能

### ISSUE THREAD

**Issue by earthjasonlin** [eyebluecn/tank#178]
希望能增加针对每一个用户单独限速功能，就类似于空间限制功能。
非常感谢

**Comment by zicla** [comment]
> 希望能增加针对每一个用户单独限速功能，就类似于空间限制功能。 非常感谢

目前还没有计划做限速功能。 因为限速功能是一个商业化的功能，会新增很多模块进来， 后续留意我们的计划吧。 

空间功能已经在4.0.0版本中支持了，将于近期发布，请关注群里消息。
