### ISSUE TITLE
希望加入后台设置https功能

### ISSUE THREAD

**Issue by AlairEileen** [eyebluecn/tank#183]
现在http很多设备都会受限，所以希望开发者加上https后台的设置
还有如果前端文件能够分个类就更好了

**Comment by zicla** [comment]
> 现在http很多设备都会受限，所以希望开发者加上https后台的设置 还有如果前端文件能够分个类就更好了

https请自行通过nginx配置，蓝眼云盘不打算重复造这个轮子。 另外对文件进行分类的功能列入到了开发计划中，在后续的版本中支持。
