### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by 1-riverfish** [eyebluecn/tank#19]
请问  私有文件 和 公有文件的区别在哪里？

**Comment by zicla** [comment]
> 请问 私有文件 和 公有文件的区别在哪里？

对于“公有文件”只要获取到了url，任何人都能通过url访问到资源。

对于“私有文件”，有了这个url还不能访问，还需要一个downloadToken，这个token会有有效期的。

如此设计主要是满足对不同文件访问级别控制的需求。

具体用法可以参考[这个文档](https://github.com/eyebluecn/tank/blob/master/build/doc/alien_zh.md)

@1-riverfish
