### ISSUE TITLE
[功能建议] 使用 docker-compose.yml 进行一件安装

### ISSUE THREAD

**Issue by long-fu** [eyebluecn/tank#194]
[功能建议] 使用 docker-compose.yml 进行一件安装

**Comment by zicla** [comment]
> [功能建议] 使用 docker-compose.yml 进行一件安装

以前是支持过 docker-compose.yml 的，但是mysql数据库不建议安装在docker中，而且很多时候docker需要按照自己的喜好去编排，所以取消了docker-compose.yml 的默认支持。 如果有需要，请自行编写docker-compose.yml 。
