### ISSUE TITLE
希望修改文件外链名称统一支持。

### ISSUE THREAD

**Issue by wokaotianshi123** [eyebluecn/tank#195]
外链时，现在为https://xxxx/api/alien/download/d57ab41d-25a0-4934-4f0c-e1fccf94cfdb/xx.txt
中间的download之后为随机uuid，希望固定为目录
每个文件的随机值不一样，不方便外链共享
如https://xxxx/api/alien/download/AAAA/xx.txt
其中AAAA为网盘的目录。

**Comment by zicla** [comment]
这个短期内无法支持，uuid是文件唯一识别标识，我们不希望直接暴露文件存储位置。
