### ISSUE TITLE
[WebDAV] 无法进入空文件夹

### ISSUE THREAD

**Issue by kuailexs** [eyebluecn/tank#197]
# 使用版本：3.1.6
# webdav 进空文件夹提示验证错误

- 在网站上建的新空文件夹，在手机端ES文件文件浏览器中，无法进该空文件夹。提示连接失败：提示检查是否授权、提示检查账号信息
- 在win电脑上用 WinSCP也是一样提示
- 在winscp和ES上建文件夹，可以进去，但是里面还有一个文件夹同名的文件夹。

## 在ES文件浏览器中点击具体文件，均会加载失败

**Comment by zicla** [comment]
我使用 4.0.4版本测试了，正常，请考虑升级到最新版本。 升级方法参考[这里](https://tank-doc.eyeblue.cn/upgrade/migrate-3.1.x-to-4.0.x.html)

![436c2d04a62475a5602b77c528abcb3](https://github.com/user-attachments/assets/341abd0f-4095-4814-b75f-252fe1c65842)
![7ec0c442c3efc7cc3edb924bd1d5aac](https://github.com/user-attachments/assets/c436a4ed-d4ca-4cd2-8135-e8861db6759e)
![image](https://github.com/user-attachments/assets/cad8b0f5-6577-42a0-9691-2477308b0911)
