### ISSUE TITLE
通过kkfileview预览共享文件会报错

### ISSUE THREAD

**Issue by luolovehk** [eyebluecn/tank#199]
http://your-kkfileview-domain/onlinePreview?url={b64Url}

通过这种方式预览共享文件会提示下面这个错误，登陆后在我的文件夹内预览就没问题。顺便建议提取码的选项是否能让用户选择是否需要提取码访问。

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Apr 25 15:06:25 UTC 2023
There was an unexpected error (type=Internal Server Error, status=500).

**Comment by qiaoshengyu** [comment]
确实，我也遇到了同样的问题，不知道现在有无解决方案

**Comment by zicla** [comment]
如果你希望无权限控制，那么可以把文件调成“公有文件”。那么预览的时候自然不会有权限拦截问题了。
