### ISSUE TITLE
一般人还安装不了

### ISSUE THREAD

**Issue by lslove10010** [eyebluecn/tank#211]
[ERROR]21:59:55 tank_config.go:69 MysqlUsername  is not configured
[ERROR]21:59:55 tank_config.go:155 config file not integrity, installation will start!
[INFO ]21:59:55 tank_application.go:153 App started at http://localhost:6010
2023/07/21 21:59:55 ListenAndServe: listen tcp :6010: bind: address already in use
无法打开

**Comment by zicla** [comment]
> [ERROR]21:59:55 tank_config.go:69 MysqlUsername is not configured [ERROR]21:59:55 tank_config.go:155 config file not integrity, installation will start! [INFO ]21:59:55 tank_application.go:153 App started at http://localhost:6010 2023/07/21 21:59:55 ListenAndServe: listen tcp :6010: bind: address already in use 无法打开

你的6010端口被其他程序占用了，你可以在conf/tank.json中修改ServerPort为其他端口，然后重启即可。

**Comment by lslove10010** [comment]
ok,大佬还有就是后期有计划支持onedrive,阿里，s3等网络储存么？



在 2023-07-22 17:10:45，"eyeblue" ***@***.***> 写道：

[ERROR]21:59:55 tank_config.go:69 MysqlUsername is not configured [ERROR]21:59:55 tank_config.go:155 config file not integrity, installation will start! [INFO ]21:59:55 tank_application.go:153 App started at http://localhost:6010 2023/07/21 21:59:55 ListenAndServe: listen tcp :6010: bind: address already in use 无法打开

你的6010端口被其他程序占用了，你可以在conf/tank.json中修改ServerPort为其他端口，然后重启即可。
