### ISSUE TITLE
加载比较慢

### ISSUE THREAD

**Issue by coffeerr2004001** [eyebluecn/tank#213]
![屏幕截图 2023-07-23 183611](https://github.com/eyebluecn/tank/assets/3371079/91ae54a5-bc44-4702-8136-cab1e61d40ea)
刚装了docker版本, 似乎比较首页加载比较慢, 加载后正常了.

**Comment by zicla** [comment]
前端资源打包出来就比较大，可以参考文档，配置压缩。 压缩后会快很多。  https://tank-doc.eyeblue.cn/advance/question.html#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AEnginx%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%EF%BC%9F
