### ISSUE TITLE
Installation & Stop service problem on Ubuntu 16.04

### ISSUE THREAD

**Issue by heiybb** [eyebluecn/tank#22]
- **常规安装**  

按照配置部署后
使用./startup.sh
显示Start tank successfully然而打不开界面
浏览器错误类型ERR_CONNECTION_TIMED_OUT

尝试直接执行./tank报错：
配置文件格式错误！
panic: 配置文件格式错误！

goroutine 1 [running]:
tank/rest.LogPanic(0x848920, 0x94cfe0)
	/data/golang/src/tank/rest/util_log.go:49 +0xc1
tank/rest.LoadConfigFromFile()
	/data/golang/src/tank/rest/config.go:168 +0x1f7
tank/rest.PrepareConfigs()
	/data/golang/src/tank/rest/config.go:321 +0x26
main.main()
	/data/golang/src/tank/main.go:14 +0x34
- **Docker-compose**  

根据需求修改了样例yml文件后执行出现报错
ERROR: manifest for eyeblue/tank:1.0.5 not found
直接使用样例文件出现同样错误

**Comment by zicla** [comment]
Fixed this issue in tank 2.0.0
