### ISSUE TITLE
希望能保留文件的真实元信息（比如创建时间）

### ISSUE THREAD

**Issue by qq77522980** [eyebluecn/tank#223]
当我上传文件或者扫描已存在的文件，网盘中会显示文件的修改日期，但是这个日期是文件的上传日期，并非文件的真实修改日期。
比如我本地文件的创建日期是8.17，今天是8.30，我上传或者扫描后文件会显示8.30而非8.17。
1、希望能增加显示文件真实创建日期的功能；
2、顺带希望能增加查看文件EXIF信息的功能，比如照片的GPS，分辨率，等等。
感谢。

**Comment by zicla** [comment]
1. 创建时间指的是该条记录在数据库中创建的时间。
2. 目前不支持查看文件EXIF信息，如果需要查看这些信息请下载到本地通过“属性”查看吧，1中提到的本地创建时间同理。

蓝眼云盘暂不计划此项功能
