### ISSUE TITLE
建议优化文件分享里面的下载按钮，下载的文件名和分享文件名不一样,名字都是archive.zip

### ISSUE THREAD

**Issue by bit15k** [eyebluecn/tank#228]
![image](https://github.com/eyebluecn/tank/assets/29975541/ecbf6956-bd3e-4874-885d-9e553f8013d5)

**Comment by zicla** [comment]
分享一起下载本职上多个文件一起下载，后台是打包到一个压缩包后，返回回来，因为文件名字情况太多，不规整，所以统一返回archive.zip。

至于你下面说正常的那个，是因为单文件就会直接保持文件名。
