### ISSUE TITLE
个人文件下的目录，只要获得路径就可以在其他浏览器下载，安全隐患

### ISSUE THREAD

**Issue by liangdy678** [eyebluecn/tank#229]
![image](https://github.com/eyebluecn/tank/assets/103975033/507a7eb5-a385-4f84-a47f-554fcd649504)
我们分享或者泄露了这个地址，在其他浏览器就可以下载这个文件夹，不像分享链接，可以取消分享，这个直接裸奔，不知道是不是个安全问题？

**Comment by zicla** [comment]
感谢你的issue，该问题已经在4.0.2版本中修复了。 https://github.com/eyebluecn/tank/releases/tag/v4.0.2

 因为路径中带有uuid，所以路径不会很好识别，但是为了安全起见，建议将存量的文件夹都设置为隐私。

```sql

UPDATE tank40_matter SET privacy = 1 WHERE dir = 1;
```
