### ISSUE TITLE
下载不能均速

### ISSUE THREAD

**Issue by hiccup-xu** [eyebluecn/tank#230]
测试时发现，多个文件同时下载，前两个文件会把带宽用完，导致第三个以后的文件速度直接为零

![VeryCapture_20231017155027](https://github.com/eyebluecn/tank/assets/75781702/da8b8629-2390-4696-adfb-0a0e469f79e1)

![VeryCapture_20231017154913](https://github.com/eyebluecn/tank/assets/75781702/96fb7335-8ee4-4cf8-98e7-19acc542c4bc)

**Comment by hiccup-xu** [comment]
win10环境

**Comment by hiccup-xu** [comment]
mysql8

**Comment by hiccup-xu** [comment]
这个项目还有人在维护么？

**Comment by hiccup-xu** [comment]
求回复

**Comment by hiccup-xu** [comment]
求更新

**Comment by hiccup-xu** [comment]
求更新

**Comment by zicla** [comment]
关于性能分配、关于cpu使用计划 等特性，蓝眼云盘暂不计划做
