### ISSUE TITLE
回收站，重新上傳，提示檔案已存在

### ISSUE THREAD

**Issue by HuJK** [eyebluecn/tank#232]
回收站，重新上傳，提示檔案已存在

復現方法:
1. 上傳 aaa.txt
2. 刪除 aaa.txt ，選擇移至回收站
3. 再次上傳新版 aaa.txt ，提示文件已存在

預期行為:
1. 上傳成功
2. 回收站那邊保存 original path ，復原時如果原路徑不存在/檔案已存在，提示重新選擇路徑/檔名
3. 回收站是特殊資料夾。即使回收站已經有 aaa.txt ，再次把 aaa.txt 移至回收站，不應該發生衝突。

還有一個建議，```request *http.Request``` 應該止於 controller，不應該把使用者前端傳過來的原始請求直接丟給內層的 model

**Comment by zicla** [comment]
回收站的逻辑，因为存储结构的限制，不好调整。 目前已增加了相应的提示。

关于Controller和model分层的问题，本项目采用了最简单的MVC分层，没有使用领域驱动设计。 关于领域驱动设计可以看一下我写的文章，后面可以交流。  https://mp.weixin.qq.com/s/HMLpjcE0UENUTfMK0Z9n8A
