### ISSUE TITLE
用户图像优化

### ISSUE THREAD

**Issue by Manly-Ford** [eyebluecn/tank#236]
上传用户图像之后，文件保存在“个人文件”存储里面；建议单独开辟空间保存，图像不作为用户文件存储，这样文件删除了之后用户图像就无法正常显示。

**Comment by zicla** [comment]
蓝眼云盘所有文件都是显示存储，不去单独开辟空间存储。 如果不希望放到“个人文件”中，你可以在上传头像的地方，直接使用url.
