### ISSUE TITLE
WebDav输入管理员用户名和密码后，提示这样的东西

### ISSUE THREAD

**Issue by nanGuoMM** [eyebluecn/tank#258]
![截图20240712081533(1)](https://github.com/user-attachments/assets/ec28f440-2c30-408e-b95a-af7ac4698ef0)

**Comment by nanGuoMM** [comment]
用户名密码都是对的

**Comment by zicla** [comment]
> 用户名密码都是对的

WebDav 只能用Client来承接，不能在网页访问。
