### ISSUE TITLE
ERROR: manifest for eyeblue/tank:1.0.5 not found

### ISSUE THREAD

**Issue by fuzqing** [eyebluecn/tank#26]
额，可能是作者误删了，还是忘了push，`hub.docker.com` 最新版本只有 `1.0.3`
```
docker pull eyeblue/tank:1.0.5
ERROR: manifest for eyeblue/tank:1.0.5 not found
```

**Comment by zicla** [comment]
> 额，可能是作者误删了，还是忘了push，`hub.docker.com` 最新版本只有 `1.0.3`
> 
> ```
> docker pull eyeblue/tank:1.0.5
> ERROR: manifest for eyeblue/tank:1.0.5 not found
> ```

感谢反馈，我紧急修复一下

**Comment by zicla** [comment]
再次感谢你的反馈，目前已经push到了hub中，并且自测一切ok。
