### ISSUE TITLE
Office预览功能不够强大

### ISSUE THREAD

**Issue by zicla** [eyebluecn/tank#29]
目前Office文件预览功能借助了微软的开放接口，要求微软的服务器要能拉取到对应的office文件才可以预览，这也就使得本地部署的蓝眼云盘无法预览，而且最大限制还不能超过10M，这样子预览的能力就比较弱了。 考虑在下个版本专门针对文件在线预览功能新增一些特殊处理的接口~

**Comment by zhuwei** [comment]
10M有点太低。。。

**Comment by lvbuwei** [comment]
对，最好是增加特殊处理接口，这样，不同的文件处理不同的预览，专用的文件就更容易集成进去。

**Comment by zicla** [comment]
最新版本将会支持自定义office预览接口。
