### ISSUE TITLE
考虑添加Sqlite支持

### ISSUE THREAD

**Issue by zicla** [eyebluecn/tank#32]
如果支持Sqlite，那么将会是一些部署到arm板上的同学的福音。

同时数据库连接的健壮性上需要做进一步增强，比如加入重试机制，断开报错提示等。

**Comment by zhuwei** [comment]
支持！

**Comment by zicla** [comment]
> 预计开始时间什么时候？

预计在2.0正式发布之前支持

**Comment by zicla** [comment]
经过调研，Sqlite 目前是 https://github.com/mattn/go-sqlite3 作为链接库，但是该库又要依赖gcc，从而引入这个库之后导致整个构建链变得更加复杂，更加重了；经过权衡，决定 2.0先不支持 Sqlite了，抱歉~

**Comment by zicla** [comment]
> 如果支持Sqlite，那么将会是一些部署到arm板上的同学的福音。
> 
> 同时数据库连接的健壮性上需要做进一步增强，比如加入重试机制，断开报错提示等。

目前蓝眼云盘支持数据库重连~
