### ISSUE TITLE
建议增加简单用户分组功能，并且根据用户分组产生共享目录，成员可以往共享目录共享与下载文件

### ISSUE THREAD

**Issue by intionwun** [eyebluecn/tank#33]
建议增加简单用户分组功能，并且根据用户分组产生共享目录，成员可以往共享目录共享与下载文件

**Comment by zicla** [comment]
目前我认为这个功能可能脱离了云盘的基本功能，所以想征求一下大家的意见，有类似需求的朋友可以在这个issue下面响应一下。

**Comment by 18633847058** [comment]
我觉得可以增加这个功能，很不错

**Comment by sunsulei** [comment]
建议+1.
如果只是需要一个网盘,其实百度或者其他网盘都是不错的选择,最多数据加密上传.

**Comment by zicla** [comment]
3.0.0.Beta2 已经添加了用提取码分享文件了，该功能不再开发。添加钉钉群体验beta版本
