### ISSUE TITLE
mysql出错

### ISSUE THREAD

**Issue by teg1c** [eyebluecn/tank#34]
Error 1366: Incorrect string value: '\xE8\x93\x9D\xE7\x9C\xBC...' for column 'name' at row 1

**Comment by teg1c** [comment]
/api/preference/fetch

**Comment by teg1c** [comment]
解决了，修改tank20_preference表name字段编码为utf8
`alter table tank20_preference change name name varchar(45) character set utf8 not null default '';`

**Comment by teg1c** [comment]
还有一个表也需要修改
`alter table tank20_matter change name name varchar(255) character set utf8 not null default '';`

**Comment by zicla** [comment]
加到钉钉群里 我给你具体看一下

**Comment by zicla** [comment]
在数据库建库的时候选用Utf8编码，表的编码就回自动和数据库一样，就不会出现编码问题了。
