### ISSUE TITLE
tank.json里都有哪些参数，怎么修改监听地址

### ISSUE THREAD

**Issue by kybom** [eyebluecn/tank#35]
有没有tank.json支持的参数列表?
要用caddy代理，所以只想监听127.0.0.1

**Comment by zicla** [comment]
> 有没有tank.json支持的参数列表?
> 要用caddy代理，所以只想监听127.0.0.1

tank.json中在安装的时候有两个字段：ServerPort表示监听的端口默认为6010，MatterPath表示上传文件存放的位置，默认为空表示存于安装目录下的matter文件夹中。

如果只想监听到127.0.0.1那么就应该将ServerPort值修改为80。一般说来这个端口值可以不用修改的，你可以通过配置一个反向代理，来让所有外部请求都访问到80端口。如果还有疑惑可以加钉钉群。

**Comment by kybom** [comment]
是这样修改吗？
```
"ServerPort": "127.0.0.1:6010"
```
还是这样修改？
```
"ServerHost": "127.0.0.1"
```
