### ISSUE TITLE
最好添加开机启动的方法

### ISSUE THREAD

**Issue by zicla** [eyebluecn/tank#36]
部分用户反馈，需要设置开机启动~ 包括windows平台按照服务的方式启动，centos，ubuntu开机自启动。

**Comment by yufeng94** [comment]
这个不需要吧，linux可以利用systemd工具完成服务自启。
在  /etc/systemd/system/  目录下新建tank.service文件，把以下内容放进去，用systemctl命令就可以控制云盘的启动关闭以及开机自启了。

[Unit]
Description=tank
After=network.target
Wants=network.target

[Service]
Type=simple
PIDFile=/var/run/tank.pid
ExecStart=/root/tank-2.0.0/service/startup.sh
ExecStop=/root/tank-2.0.0/service/shutdown.sh
ExecReload=/bin/kill -HUP $MAINPID
RestartPreventExitStatus=23
Restart=always

[Install]
WantedBy=default.target
EOF

**Comment by zicla** [comment]
> 这个不需要吧，linux可以利用systemd工具完成服务自启。
> 在 /etc/systemd/system/ 目录下新建tank.service文件，把以下内容放进去，用systemctl命令就可以控制云盘的启动关闭以及开机自启了。
> 
> [Unit]
> Description=tank
> After=network.target
> Wants=network.target
> 
> [Service]
> Type=simple
> PIDFile=/var/run/tank.pid
> ExecStart=/root/tank-2.0.0/service/startup.sh
> ExecStop=/root/tank-2.0.0/service/shutdown.sh
> ExecReload=/bin/kill -HUP $MAINPID
> RestartPreventExitStatus=23
> Restart=always
> 
> [Install]
> WantedBy=default.target

对，就是这个service，到时候我放到文档中，用户可以自行添加。

**Comment by zicla** [comment]
开机启动的方法已经添加在了文档中，可以参考这里： https://tank-doc.eyeblue.cn/zh/basic/install.html#linux

**Comment by XiaoPika** [comment]
@zicla 能不能提供windows的后台运行和开机自启的功能？借助第三方工具不容易实现

**Comment by XiaoPika** [comment]
https://natapp.cn/article/windows_service 
借助这个网站提供的 nssm 工具完成

**Comment by zicla** [comment]
> https://natapp.cn/article/windows_service
> 借助这个网站提供的 nssm 工具完成

@XiaoPika 最近两天我把windows的后台运行和开机启动方法补充到文档中。

**Comment by XiaoPika** [comment]
> @XiaoPika 最近两天我把windows的后台运行和开机启动方法补充到文档中。

感谢
