### ISSUE TITLE
关于文件存储位置的问题

### ISSUE THREAD

**Issue by encofcomic** [eyebluecn/tank#43]
请问现在文件存储在那个文件夹当中？使用docker的时候希望能够映射到宿主系统的文件夹中方便做大小管理，迁移和备份。
也希望这个能写入文档中去。

感谢您的回复
Susan
19/4/10

**Comment by zicla** [comment]
目前正在重构目录结构，下个版本将按照物理目录存储。

**Comment by zicla** [comment]
3.0.0.Beta2 已经完成了重构，添加钉钉群体验
