### ISSUE TITLE
安装完成无法正常使用

### ISSUE THREAD

**Issue by htg8208836** [eyebluecn/tank#46]
docker方式部署，建立完管理员帐号提示“没有找到能够处理 /api/install/finish的方法”

**Comment by htg8208836** [comment]
Error 1366: Incorrect string value: '\xE8\x93\x9D\xE7\x9C\xBC...' for column 'name' at row 1

**Comment by zicla** [comment]
> Error 1366: Incorrect string value: '\xE8\x93\x9D\xE7\x9C\xBC...' for column 'name' at row 1

这个一般是你的数据库没有指定为utf-8格式导致的。

**Comment by zicla** [comment]
3.0.0.Beta2 重构了安装程序，添加钉钉群体验
