### ISSUE TITLE
关于用户管理的2个问题

### ISSUE THREAD

**Issue by huawuya** [eyebluecn/tank#52]
1. 只能禁用用户，没找到删除用户的地方
2. 被禁用的用户只要不退出登录，就可以一直继续使用

**Comment by zicla** [comment]
ok 删除用户和禁用用户的功能在下个小版本完善。

**Comment by zicla** [comment]
删除用户的功能暂不提供。修复了禁用的问题。

**Comment by zicla** [comment]
Tank3.0.2已修复禁用用户问题。
