### ISSUE TITLE
如何更新至最新版本

### ISSUE THREAD

**Issue by yufeng94** [eyebluecn/tank#53]
已经安装了2.0版本的软件，而且存了一些文件，想要使用最新版，只能重新安装吗？

**Comment by zicla** [comment]
2.0 升级到3.0需要重新组织物理目录结果，我又写了一个迁移程序，但是文档中还没有补充出来。静等两天。  https://tank-doc.eyeblue.cn/

**Comment by zicla** [comment]
版本迁移请参考这里的文档： https://tank-doc.eyeblue.cn/zh/advance/migrate.html
