### ISSUE TITLE
希望增加项目的context-path

### ISSUE THREAD

**Issue by sunsulei** [eyebluecn/tank#54]
https://tank-doc.eyeblue.cn/zh/advance/question.html#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AEnginx%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%EF%BC%9F
如果我同个域名同个端口需要转发到多个不同的应用,只能通过`context-path`去区分不同的应用.
希望能提供个配置,默认为`/`即可.

**Comment by zicla** [comment]
context-path 蓝眼云盘是不会提供的，这个可以使用Nginx的反向代理来完成。 一个nginx下面可以根据目录挂多个网站。

**Comment by sunsulei** [comment]
@zicla Nginx不用子域名的形式，能通过目录进行跳转？
