### ISSUE TITLE
希望增加匿名登录

### ISSUE THREAD

**Issue by sky5454** [eyebluecn/tank#58]
这个做本地网盘的需求远大于做公网网盘，所以匿名登录是非常必要的，另外，文档并没有太多关于调整配置文件的说明（这个是为什么呢）

**Comment by zicla** [comment]
匿名登录短期内没有打算做，如果有需要的话，可以适当进行二次开发。 配置项本身就没有几项，基本都是在安装的过程中引导创建好了。
