### ISSUE TITLE
请求添加扫描本地文件功能

### ISSUE THREAD

**Issue by loeveo** [eyebluecn/tank#61]
希望大佬可以添加一个扫描本地存储目录文件的功能，因为这样可以直接挂在其他的网盘或者FTP之类的过去 然后进行识别. 扫描本地存储目录内的文件添加到数据库当中

**Comment by muxiaozi** [comment]
目前有一个命令可以大致实现你的需求 [映射本地文件映射](https://tank-doc.eyeblue.cn/zh/advance/cli.html#%E6%98%A0%E5%B0%84%E6%9C%AC%E5%9C%B0%E6%96%87%E4%BB%B6%E6%98%A0%E5%B0%84)

**Comment by haitao9491** [comment]
同感，请求添加此功能（个人感觉很重要）。
用处：
    在蓝眼网盘出现问题必须重新搭建网盘环境的时候，如果将文件重新一个个上传很不现实。如果在命令行使用“映射本地文件映射”时又必须为“管理员”用户，那么普通用户的添加完全没有意义了
    其次，如果有大量文件需要上传时(如备份/恢复数据时)，如果为管理员这时候在后台操作明显最方便，但如果后台的操作完成后前端不能刷新文件变化，那也没有意义

**Comment by chenyue404** [comment]
> 
> 
> 目前有一个命令可以大致实现你的需求 [映射本地文件映射](https://tank-doc.eyeblue.cn/zh/advance/cli.html#%E6%98%A0%E5%B0%84%E6%9C%AC%E5%9C%B0%E6%96%87%E4%BB%B6%E6%98%A0%E5%B0%84)

不是很明白这个功能的作用。尝试了一下，感觉就是把其他地方的文件复制过来了呢？而不是我预期的类似软链接的功能。

**Comment by adian265** [comment]
貌似确实是重新copy了一份，不是真正的映射呀

**Comment by zicla** [comment]
扫描文件功能在3.1.0中已新增。
