### ISSUE TITLE
webdav功能有问题

### ISSUE THREAD

**Issue by chaosye0** [eyebluecn/tank#64]
用的软件是zotero，同步文献用的webdav，用坚果云，nextcloud的webdav都正常，填入这个网盘的webdav地址就不行，如图
![image](https://user-images.githubusercontent.com/30192801/66678095-b14aca00-ec9d-11e9-836d-c8e928b06bb4.png)
然后我用demo的webdav地址同样不行。
最后试了一下win10直接挂载远端vps的webdav, 能挂载上，也能读取数据， 但是往里面复制文件就有问题，哪怕新建文件也会报错
![image](https://user-images.githubusercontent.com/30192801/66678291-1f8f8c80-ec9e-11e9-87d6-67683d1d7006.png)
求解决，另外这个网盘网页响应速度真的好快，甩nextcloud几十条街哈哈

**Comment by zicla** [comment]
你提出的问题我已知晓，目前webdav对有些客户端的支持可能还不够好。 你可以参考这个文档里面的webdav客户端先使用应急，后续版本我们会对webdav能力增强的。 https://tank-doc.eyeblue.cn/zh/advance/webdav.html#%E4%BD%BF%E7%94%A8%E5%8D%95%E7%8B%AC%E7%9A%84%E5%9F%9F%E5%90%8D%E4%BD%9C%E4%B8%BAwebdav%E5%9C%B0%E5%9D%80 @chaosye0

**Comment by chaosye0** [comment]
> 后续版本我们会对w

好的，期待完善，这个网盘真的速度快，希望做好做完善

**Comment by zicla** [comment]
WebDav能力在3.1.0中得到了大幅增强，如果还有问题，请再开issue
