### ISSUE TITLE
增加回收箱功能的建议

### ISSUE THREAD

**Issue by amazingyou2008** [eyebluecn/tank#65]
楼主：

非常感谢提供一款轻快的基于Go语言开发的云盘。试用体检非常不错。

但有时候误删除一些文件，日后需要恢复，这时回收箱的重要作用体现出来。

希望楼主有空增加回收箱功能。

祝此项目越来越好。

**Comment by zicla** [comment]
3.1.0版本即将发布，里面包含回收站功能。
