### ISSUE TITLE
3.0.6版本，手机浏览器访问，视频播放失败

### ISSUE THREAD

**Issue by yanjingtu** [eyebluecn/tank#67]
小米6X，自带的小米浏览器
不全屏播放时，没有具体的提示，时间条为0，播放进度也是0。全屏播放，显示视频不存在。
还有，那个“关于”弹出窗口，能不能加上云盘的版本号？
话说用手机上传视频的速度太快了。。快到反应不过来。
tank-3.0.6，下载源码后自己编译的
编译和运行设备环境：arm-v7l，1G内存
==> ~# go version
go version go1.13.1 linux/arm
==> ~#
跑起来一点都不卡，比起nextcloud性能好太多

**Comment by zicla** [comment]
视频的播放依赖于手机浏览器对于视频文件的支持程度，3.1.0中将会支持自定义预览引擎，到时候可以指定自己的视频预览引擎。3.1.0即将发布。
