### ISSUE TITLE
js、font等资源文件较大，带宽小点的服务器响应太慢

### ISSUE THREAD

**Issue by iniwf** [eyebluecn/tank#70]
![image](https://user-images.githubusercontent.com/7352346/67268521-455f3180-f4e7-11e9-8a43-3e4cbeec2d80.png)

**Comment by zicla** [comment]
前端在3.1.0版本中使用了react进行重构，目前资源大小在1M了。 3.1.0即将发布。 你也可以通过在nginx中配置资源压缩来加速。  [参考文档](https://tank-doc.eyeblue.cn/advance/question.html#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AEnginx%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%EF%BC%9F)
