### ISSUE TITLE
/install/index页面能直接访问，不会造成安全问题吗？

### ISSUE THREAD

**Issue by zhuziyi1989** [eyebluecn/tank#74]
/install/index页面能直接访问，不会造成安全问题吗？

**Comment by dairymix** [comment]
我去 还真的是。。赶紧测试一下。。
容器化部署的话 通过内部网络限制数据库出站链接的方式不知道能否规避？

**Comment by zicla** [comment]
后端接口在安装完成后便不能请求安装相关的接口了。 这里只是前端路由还保留着，不会有安全问题。
