### ISSUE TITLE
异常中断问题

### ISSUE THREAD

**Issue by devopscool** [eyebluecn/tank#77]
当上传大文件时，比如超过1G 的文件，会异常中断，log 异常如下：
[ERROR]22:31:35 tank_router.go:98: panic on matter_controller.go:227 multipart: NextPart: bufio: buffer full
[INFO ]22:31:35 footprint_service.go:91: Ip:10.101.218.133 Cost:160532 Uri:/api/matter/upload Params:{}

**Comment by zicla** [comment]
从报错信息看来应该时机器内存太小了， 大文件相关体验已经优化了，请下载 3.1.2版本
