### ISSUE TITLE
希望增加将文件夹共享给不同的用户的功能。

### ISSUE THREAD

**Issue by slitilanber** [eyebluecn/tank#79]
如题，将user1的目录共享给user2。user2可以和user1共同管理。这样可以只存储1份，节省磁盘空间。像nextcloud的这个功能一样。

**Comment by alalbb313** [comment]
墙裂建议添加此功能.

**Comment by adian265** [comment]
不知道在主机上链接一个文件夹是否可以实现

**Comment by zicla** [comment]
短期内暂不考虑协同管理的功能。
