### ISSUE TITLE
下载

### ISSUE THREAD

**Issue by Hanyuxiaoorz** [eyebluecn/tank#92]
可不可以搞一个下载功能，用户可以输入下载链接，然后tank可以自己把文件下载下来并存放在tank里面。

**Comment by zicla** [comment]
http://localhost:8080/advance/cli.html#%E6%8B%89%E5%8F%96%E8%BF%9C%E7%A8%8B%E6%96%87%E4%BB%B6

目前有命令行工具可以拉取url文件到tank中。
