### ISSUE TITLE
文件夹树型展示

### ISSUE THREAD

**Issue by Avey777** [eyebluecn/tank#96]
希望可以像mac系统一样展示文件层次
![image](https://user-images.githubusercontent.com/35259040/88072124-4244bf00-cba7-11ea-8d5f-82231a7768a5.png)

**Comment by zicla** [comment]
抱歉，这个短时间不会去支持。 你可以通过webdav的客户端来达到类似的效果  https://tank-doc.eyeblue.cn/advance/webdav.html
