### ISSUE TITLE
需要个一键部署脚本吗？

### ISSUE THREAD

**Issue by user1121114685** [eyebluecn/tank#98]
我使用了一下，感觉很不错。下面是我想要咨询的问题。
1.需要个一键脚本吗？linux的。
2.不能选择文件目录？我想将其他文件也导入进来：目前只看到一个映射。
3.webdav地址有点难找，应该放在醒目的地方。

**Comment by zicla** [comment]
1. 加压即可运行，不需要一键脚本。
2. 3.1.1版本已经可以选择上传文件夹了。
3. webdav一般需要的人也比较少，文档中已经有说明了。

**Comment by user1121114685** [comment]
> 1. 加压即可运行，不需要一键脚本。
> 2. 3.1.1版本已经可以选择上传文件夹了。
> 3. webdav一般需要的人也比较少，文档中已经有说明了。

1.mysql需要，Debian下的开机启动脚本
2.我的意思是，指定数据存放文件夹，不再是master/用户名
3.感谢
