### ISSUE TITLE
上传60M文件都要3，4min，卡在100% 进度

### ISSUE THREAD

**Issue by snecker** [eyebluecn/tank#99]
![image](https://user-images.githubusercontent.com/4178594/89248686-e700db00-d642-11ea-91b7-7d9a21feeb75.png)

进度条从0到100只花了10秒左右，到了100%就一直在那里等待，过了3/4分钟才提示成功

版本：3.1.0
系统：Centos7

**Comment by zicla** [comment]
参考这个issue https://github.com/eyebluecn/tank/issues/125
